source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LZCommonUtils_Example', :exclusive => true do
  pod "LZCommonUtils", :path => "../"
end

target 'LZCommonUtils_Tests', :exclusive => true do
  pod "LZCommonUtils", :path => "../"

  
end
